
# based on http://golang.org/src/cmd/goinstall/Makefile
include $(GOROOT)/src/Make.inc

TARG=gones
GOFILES=\
	nesfile.go \
	dis6502.go \
	cpu6502.go \
	gamegenie.go \
	main.go

include $(GOROOT)/src/Make.cmd
